"""Run identity and on-disk layout (Rule 34: one runId, propagated everywhere).

A run directory is the single source of truth for a clip. Every stage reads and
writes only inside it, which is what makes crashed runs resumable (SPEC §2).
"""

from __future__ import annotations

import hashlib
import json
import re
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field

from .config import StylesConfig
from .logging import RunLogger, utc_now

MANIFEST_NAME = "run.json"


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "clip"


def new_run_id(source: Path) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{slugify(source.stem)}-{stamp}-{uuid.uuid4().hex[:6]}"


def sha256_file(path: Path, chunk: int = 1 << 20) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        while block := fh.read(chunk):
            digest.update(block)
    return digest.hexdigest()


class RunManifest(BaseModel):
    """`run.json` — what this run is, decided once at intake."""

    schema_version: int = 1
    run_id: str
    created_at: str
    source_path: str
    source_sha256: str
    source_duration_s: float
    clip_title: str
    style: str
    fps: int
    backend: str
    reference_images: list[str] = Field(default_factory=list)
    # Set by verdi.loaders.merge_prompt_override when a canary comes back
    # "adjust". Points AT the override file; the original style prompt in
    # styles.yaml is never touched.
    prompt_override_source: str | None = None


@dataclass(frozen=True)
class RunPaths:
    root: Path

    @property
    def manifest(self) -> Path:
        return self.root / MANIFEST_NAME

    @property
    def source_frames(self) -> Path:
        return self.root / "frames" / "source"

    @property
    def restyled_frames(self) -> Path:
        return self.root / "frames" / "restyled"

    @property
    def audio(self) -> Path:
        return self.root / "audio.aac"

    @property
    def work(self) -> Path:
        return self.root / "work"

    @property
    def restyled_video(self) -> Path:
        return self.work / "restyled.mp4"

    @property
    def header_png(self) -> Path:
        return self.work / "header.png"

    @property
    def subtitles(self) -> Path:
        """Burned in when present. Generated by the captions stage (step 6)."""
        return self.root / "subs.srt"

    @property
    def final(self) -> Path:
        return self.root / "final_comparison.mp4"

    @property
    def scores(self) -> Path:
        """Per-frame score log (SPEC §3): one JSON object per scored frame."""
        return self.root / "scores.jsonl"

    @property
    def qc_card(self) -> Path:
        return self.root / "qc_card.json"

    @property
    def log(self) -> Path:
        return self.root / "logs" / "run.jsonl"

    def ensure(self) -> None:
        for d in (self.source_frames, self.restyled_frames, self.work, self.log.parent):
            d.mkdir(parents=True, exist_ok=True)


@dataclass
class Run:
    """A run directory plus its manifest and logger."""

    paths: RunPaths
    manifest: RunManifest
    logger: RunLogger

    @property
    def run_id(self) -> str:
        return self.manifest.run_id

    def save(self) -> None:
        self.paths.manifest.write_text(self.manifest.model_dump_json(indent=2) + "\n")

    @classmethod
    def create(
        cls,
        *,
        source: Path,
        style: str,
        fps: int,
        backend: str,
        clip_title: str,
        duration_s: float,
        styles: StylesConfig,
        runs_dir: Path | None = None,
        echo: bool = True,
    ) -> "Run":
        styles.profile(style)  # unknown style is a hard failure, before any I/O
        base = runs_dir if runs_dir is not None else styles.output.runs_dir
        run_id = new_run_id(source)
        paths = RunPaths(Path(base) / run_id)
        paths.ensure()
        manifest = RunManifest(
            run_id=run_id,
            created_at=utc_now(),
            source_path=str(source.resolve()),
            source_sha256=sha256_file(source),
            source_duration_s=duration_s,
            clip_title=clip_title,
            style=style,
            fps=fps,
            backend=backend,
        )
        run = cls(paths=paths, manifest=manifest, logger=RunLogger(run_id, paths.log, echo))
        run.save()
        return run

    @classmethod
    def load(cls, root: Path, echo: bool = True) -> "Run":
        paths = RunPaths(root)
        if not paths.manifest.is_file():
            raise FileNotFoundError(
                f"{root} is not a ClayPipe run directory (no {MANIFEST_NAME}). "
                "Run `claypipe intake <video>` first."
            )
        manifest = RunManifest.model_validate(json.loads(paths.manifest.read_text()))
        paths.ensure()
        return cls(paths=paths, manifest=manifest, logger=RunLogger(manifest.run_id, paths.log, echo))


def resolve_run(target: Path, runs_dir: Path) -> Path:
    """Accept either a run directory or a bare run id."""
    if (target / MANIFEST_NAME).is_file():
        return target
    candidate = runs_dir / target.name
    if (candidate / MANIFEST_NAME).is_file():
        return candidate
    raise FileNotFoundError(f"no run found at {target} or {candidate}")
